name: Build
on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm ci
      - run: npm run build
      - name: Run Tests
        run: npm test
        env:
          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
          TEST_MONGO_DATABASE: ${{ secrets.TEST_MONGO_DATABASE }}
          TEST_MONGO_HOST: ${{ secrets.TEST_MONGO_HOST }}
