name: Build
on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm ci
      - run: npm run build
      - run: npm test
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
